### ISSUE TITLE
'tab-on' Class for screen_type 'component' 

### ISSUE THREAD

**Issue by levybee** [uncatcrea/wpak-tabs-themes#8]
Hi,   I think I have found an issue(bug) on this theme. For current_screen.screen_type 'custom-component' 'tab on' class is not set when the tab is clicked. I have to change the below line in functions.js from:
 
  
        // A Post List is displayed
        if( current_screen.screen_type == "list"){

   to:

    // A Post List is displayed
        if( current_screen.screen_type == "list" || current_screen.screen_type == "custom-component" ){

..for it to work.

**Comment by blupu** [comment]
You're totally right. However, you may have custom component that are not lists.

**Comment by levybee** [comment]
I see
